/**
 * TypeScript type definitions for Chat Widget
 * Based on data-model.md specifications
 */

/**
 * Represents a single message in a conversation
 */
export interface ChatMessage {
  id: string; // Unique message identifier (client-generated UUID)
  text: string; // Message content
  sender: 'user' | 'assistant'; // Message sender
  timestamp: string; // Message creation time (ISO 8601)
  status?: 'sending' | 'sent' | 'error'; // Message delivery status
  citations?: Citation[]; // Source references (assistant messages only)
  error?: ErrorInfo; // Error details (if status is "error")
}

/**
 * Represents a reference to textbook content
 */
export interface Citation {
  id?: string; // Optional citation identifier
  text: string; // Citation display text (e.g., "Module 1, Section 2.3")
  url: string; // Link to referenced content (relative or absolute)
  chapter?: string; // Optional chapter/module identifier
  section?: string; // Optional section identifier
  page?: number; // Optional page number if applicable
}

/**
 * Represents error information for failed operations
 */
export interface ErrorInfo {
  type: 'network' | 'timeout' | '4xx' | '5xx' | 'validation'; // Error category
  message: string; // User-friendly error message
  code?: number; // HTTP status code (for 4xx/5xx errors)
  retryable: boolean; // Whether error can be retried
  timestamp: string; // Error occurrence time
}

/**
 * Represents an active conversation session
 */
export interface ChatSession {
  sessionId: string; // Unique session identifier generated by backend
  createdAt: string; // Session creation timestamp (ISO 8601)
  lastActivity?: string; // Last message timestamp
  messageCount?: number; // Total messages in session
}

/**
 * API Request interface for chat endpoint
 */
export interface ChatRequest {
  message: string; // User message (1-2000 characters)
  session_id: string; // Session identifier (UUID)
  thread_id?: string; // Optional thread ID (not used in MVP)
}

/**
 * API Response interface from chat endpoint
 */
export interface ChatResponse {
  response: string; // AI-generated response text
  citations: Citation[]; // Array of source citations
  session_id: string; // Session ID (echoed back)
  thread_id?: string; // Optional thread ID
  metadata: {
    model_used: string; // e.g., "gemini-2.5-flash"
    generation_time: number; // Response time in seconds
  };
}

/**
 * Component state structure for ChatWidget
 */
export interface ChatWidgetState {
  isOpen: boolean; // Widget open/closed state
  sessionId: string | null; // Current session ID
  messages: ChatMessage[]; // Conversation messages
  isLoading: boolean; // Loading indicator state
  error: ErrorInfo | null; // Current error (if any)
  inputValue: string; // Current input field value
  characterCount: number; // Character count for validation
}

